server:
  servlet:
    context-path: /statuserver
  port: 9999
logging:
  config: classpath:logback-custom.xml
  file:
    name: /data/logs/${spring.application.name}/root.log

# 用于生成主键和二维码简码 此处在集群部署的时候machine id 一定不可重复。
code-generator:
  centerid: 0
  machineid: 0

spring:
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS              默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: file:/usr/reslog/web/build